#!/bin/bash

rev=$(git rev-parse --short HEAD |  tr -d "\n")
node build https://scheibo.github.io/boggle/ /boggle/
cp -a dist /tmp
git checkout gh-pages
cp -a /tmp/dist/* .
git add .
git commit -m "Publish: '${rev}'"
git push origin gh-pages
git checkout -